Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python39\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pdfkit
import pandas as pd

path_wkhtmltopdf = "/content/wkhtmltox_0.12.6-1.bionic_amd64.deb"
config = pdfkit.configuration(wkhtmltopdf=path_wkhtmltopdf)

data = pd.read_csv('news.csv',index_col=False)
html_string = data.to_html()
pdfkit.from_string(html_string, "Dokumen.pdf")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pdfkit\configuration.py[0m in [0;36m__init__[1;34m(self, wkhtmltopdf, meta_tag_prefix, environ)[0m
[0;32m     34[0m [1;33m[0m[0m
[1;32m---> 35[1;33m             [1;32mwith[0m [0mopen[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mwkhtmltopdf[0m[1;33m)[0m [1;32mas[0m [0mf[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     36[0m                 [1;32mpass[0m[1;33m[0m[1;33m[0m[0m

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/content/wkhtmltox_0.12.6-1.bionic_amd64.deb'

During handling of the above exception, another exception occurred:

[1;31mOSError[0m                                   Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_7336/792963454.py[0m in [0;36m<module>[1;34m[0m
[0;32m      3[0m [1;33m[0m[0m
[0;32m      4[0m [0mpath_wkhtmltopdf[0m [1;33m=[0m [1;34m"/content/wkhtmltox_0.12.6-1.bionic_amd64.deb"[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 5[1;33m [0mconfig[0m [1;33m=[0m [0mpdfkit[0m[1;33m.[0m[0mconfiguration[0m[1;33m([0m[0mwkhtmltopdf[0m[1;33m=[0m[0mpath_wkhtmltopdf[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      6[0m [1;33m[0m[0m
[0;32m      7[0m [0mdata[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[1;34m'news.csv'[0m[1;33m,[0m[0mindex_col[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pdfkit\api.py[0m in [0;36mconfiguration[1;34m(**kwargs)[0m
[0;32m     84[0m     """
[0;32m     85[0m [1;33m[0m[0m
[1;32m---> 86[1;33m     [1;32mreturn[0m [0mConfiguration[0m[1;33m([0m[1;33m**[0m[0mkwargs[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\AppData\Local\Programs\Python\Python39\lib\site-packages\pdfkit\configuration.py[0m in [0;36m__init__[1;34m(self, wkhtmltopdf, meta_tag_prefix, environ)[0m
[0;32m     36[0m                 [1;32mpass[0m[1;33m[0m[1;33m[0m[0m
[0;32m     37[0m         [1;32mexcept[0m [1;33m([0m[0mIOError[0m[1;33m,[0m [0mFileNotFoundError[0m[1;33m)[0m [1;32mas[0m [0me[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 38[1;33m             raise IOError('No wkhtmltopdf executable found: "%s"\n'
[0m[0;32m     39[0m                           [1;34m'If this file exists please check that this process can '[0m[1;33m[0m[1;33m[0m[0m
[0;32m     40[0m                           [1;34m'read it or you can pass path to it manually in method call, '[0m[1;33m[0m[1;33m[0m[0m

[1;31mOSError[0m: No wkhtmltopdf executable found: "/content/wkhtmltox_0.12.6-1.bionic_amd64.deb"
If this file exists please check that this process can read it or you can pass path to it manually in method call, check README. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
OSError: No wkhtmltopdf executable found: "/content/wkhtmltox_0.12.6-1.bionic_amd64.deb"
If this file exists please check that this process can read it or you can pass path to it manually in method call, check README. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf

